language: node_js

sudo: required

node_js:
  - 7

services:
  - docker

deploy:
  provider: heroku
  api_key: "fb7c6a6a-ca34-49e5-8e55-195e49c0e15e"
  app: "stepfighting"

script:
  - docker login --username=_ --password=$(echo $api_key) registry.heroku.com
  - docker build -t registry.heroku.com/tp-heroku-2017/web .
  - docker push registry.heroku.com/tp-heroku-2017/web

